include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_relative_imports: true
    sort_pub_dependencies: true
    always_declare_return_types: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    valid_regexps: true

