// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyACuw1WT3Njrbpz1BCRiMy91CaTqmTypKg",
  authDomain: "bishops-e48c8.firebaseapp.com",
  projectId: "bishops-e48c8",
  storageBucket: "bishops-e48c8.firebasestorage.app",
  messagingSenderId: "1021548695581",
  appId: "1:1021548695581:web:31668ee852c06bb1d7f6f4"

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACuw1WT3Njrbpz1BCRiMy91CaTqmTypKg',
    appId: '1:1021548695581:android:31668ee852c06bb1d7f6f4',
    messagingSenderId: '1021548695581',
    projectId: 'bishops-e48c8',
    storageBucket: 'bishops-e48c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACuw1WT3Njrbpz1BCRiMy91CaTqmTypKg',
    appId: '1:1021548695581:ios:31668ee852c06bb1d7f6f4',
    messagingSenderId: '1021548695581',
    projectId: 'bishops-e48c8',
    storageBucket: 'bishops-e48c8.firebasestorage.app',
    iosBundleId: 'com.example.bishops_management_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACuw1WT3Njrbpz1BCRiMy91CaTqmTypKg',
    appId: '1:1021548695581:ios:31668ee852c06bb1d7f6f4',
    messagingSenderId: '1021548695581',
    projectId: 'bishops-e48c8',
    storageBucket: 'bishops-e48c8.firebasestorage.app',
    iosBundleId: 'com.example.bishops_management_app',
  );
}
